#!/usr/bin/env python3
"""Derive the Psiphon Access logo and favicon assets from the Psiphon lockup.

Run from the repository root:

    python3 tool/teleport-google/assets/derive-logo.py
    nix shell nixpkgs#librsvg --command \
        python3 tool/teleport-google/assets/derive-logo.py --favicons

Source of truth is the lockup in the psix-v2 repository, so the artwork is not
copied by hand and cannot drift:

    ~/src/psix-v2/trees/main/web/src/psiphon-brand.ts

WHY IT WRITES UPSTREAM FILENAMES TOO. The web build stages the logo itself. The
ensure-webassets target in the Makefile copies
design/src/assets/images/agpl-{light,dark}.svg over
teleport/public/app/logo-{light,dark}.svg on every build, so the only ways to
change the logo are to patch that target or to change what those two files
contain. Measured over two years of upstream history:

    Makefile                 128 commits
    agpl-light.svg             0 commits
    agpl-dark.svg              0 commits
    favicon-{light,dark}.png   0 commits

Editing four files that upstream never touches is far cheaper to carry than one
file it touches 128 times, so this script overwrites the zero-churn asset files
and leaves the build system alone. The psiphon-* files are the canonical,
honestly named originals; the upstream-named files are generated copies. Both
come from one run, so they cannot disagree.

THE currentColor TRAP. Every path in the source lockup is fill="currentColor".
That works for inline SVG but resolves to black through an <img> reference, which
is how these files are consumed, so the dark variant would be invisible on a dark
background. Each variant therefore gets an explicit fill. The -light and -dark
suffixes name the BACKGROUND and not the ink, matching upstream, where
agpl-light.svg carries Teleport purple #512FC9 and agpl-dark.svg carries white.
"""

import argparse
import pathlib
import re
import shutil
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parents[3]
BRAND = pathlib.Path.home() / "src/psix-v2/trees/main/web/src/psiphon-brand.ts"
IMAGES = REPO / "web/packages/design/src/assets/images"
PUBLIC = REPO / "web/packages/teleport/public/app"

# Ink follows the psix light theme, where the lockup inherits the text colour.
INKS = {"light": "#000000", "dark": "#FFFFFF"}

# The glyph alone spans roughly x 0.23..156.70 and y 0.25..210.69. Centre it in a
# square box so the favicon is not lopsided.
GLYPH_VIEWBOX = "-27 0 211 211"

FAVICON_PX = 32


def load_paths():
    source = BRAND.read_text(encoding="utf8")
    match = re.search(r"const psiphonLockupMarkup = `(.*?)`;", source, re.S)
    if not match:
        sys.exit(f"could not find psiphonLockupMarkup in {BRAND}")
    lockup = match.group(1).strip()

    paths = re.findall(r"<path\b[^>]*/>", lockup)
    if len(paths) != 8:
        sys.exit(
            f"expected 8 paths, 7 wordmark letters plus 1 glyph, found {len(paths)}. "
            "The source artwork changed; check the derivation before trusting it."
        )
    viewbox = re.search(r'viewBox="([^"]+)"', lockup).group(1)
    return paths[:7], paths[7], viewbox


def render(body, box, ink):
    filled = "\n".join(p.replace('fill="currentColor"', f'fill="{ink}"') for p in body)
    return (
        "<!-- Generated by tool/teleport-google/assets/derive-logo.py. Do not edit. -->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{box}" fill="none"'
        f' role="img" aria-label="Psiphon">\n{filled}\n</svg>\n'
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--favicons",
        action="store_true",
        help="also rasterise the favicons, which needs rsvg-convert on PATH",
    )
    args = parser.parse_args()

    wordmark, glyph, viewbox = load_paths()
    written = []

    for mode, ink in INKS.items():
        lockup = IMAGES / f"psiphon-{mode}.svg"
        lockup.write_text(render(wordmark + [glyph], viewbox, ink), encoding="utf8")

        mark = IMAGES / f"psiphon-mark-{mode}.svg"
        mark.write_text(render([glyph], GLYPH_VIEWBOX, ink), encoding="utf8")

        # The file the web build actually stages. Same content, upstream's name.
        staged = IMAGES / f"agpl-{mode}.svg"
        shutil.copyfile(lockup, staged)

        written += [lockup, mark, staged]

    if args.favicons:
        if shutil.which("rsvg-convert") is None:
            sys.exit(
                "rsvg-convert not found. Re-run inside:\n"
                "  nix shell nixpkgs#librsvg --command python3 "
                "tool/teleport-google/assets/derive-logo.py --favicons"
            )
        for mode in INKS:
            for target in (
                IMAGES / f"psiphon-favicon-{mode}.png",
                PUBLIC / f"favicon-{mode}.png",
            ):
                subprocess.run(
                    [
                        "rsvg-convert",
                        "-w", str(FAVICON_PX), "-h", str(FAVICON_PX),
                        str(IMAGES / f"psiphon-mark-{mode}.svg"),
                        "-o", str(target),
                    ],
                    check=True,
                )
                written.append(target)

    for f in written:
        print(f"{f.relative_to(REPO)}  {f.stat().st_size} bytes")


if __name__ == "__main__":
    main()
