#!/usr/bin/env python3
"""Stamp the running revision into a fork-owned TypeScript constant.

Run from the repository root, before the web build:

    python3 tool/teleport-google/assets/stamp-build.py

WHY THIS EXISTS. AGPL section 13 asks for the Corresponding Source of the version
a user is actually interacting with, so a bare repository link is not quite
enough: it drifts from the deployed binary on the first commit. The login page
therefore shows the revision beside the link.

Nothing already carries that value to the browser. webConfig has no version
field, and the Vite config only defines process.env.NODE_ENV, so the alternatives
were to patch lib/web/apiserver.go, which would be a third modified upstream Go
file, or to patch the Vite config, which would be another upstream file.
Generating a fork-owned module instead costs no upstream file at all.

Note that `go build -buildvcs=false`, which this repository needs because of the
grove worktree layout, leaves Teleport's own gitref empty. So the stamp cannot be
taken from the binary either; it is read from git here.
"""

import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
OUT_REL = "web/packages/teleport/src/accessBuild.ts"
OUT = ROOT / OUT_REL

SOURCE_URL = "https://github.com/Psiphon-Inc/teleport"


def git(*args):
    return subprocess.run(
        ["git", *args], cwd=ROOT, capture_output=True, text=True, check=True
    ).stdout.strip()


def describe():
    """Return the build label, with -dirty only for a real divergence.

    `git describe --dirty` cannot be used here. This script WRITES a tracked
    file, so the first run on a clean checkout leaves the tree dirty and every
    run after that would report -dirty for a tree whose only modification is
    this script's own output. The label sits beside the section 13 source offer
    on the login page, so that false -dirty is visible to every visitor.

    The generated file is therefore excluded from the dirty test, and nothing
    else is. Any other uncommitted change is a real divergence from the source
    being offered and must still be reported.

    This test is deliberately stricter than `git describe --dirty` in one way:
    it also counts an untracked file, which git does not. An untracked file that
    the build reads is missing from the published commit, which is exactly the
    incompleteness section 13 cares about. A stray file therefore costs a
    -dirty label it did not need, and that is the safe direction to be wrong in.
    Files matched by .gitignore are not counted, so build output does not
    trigger it.
    """
    label = git("describe", "--tags", "--always")
    changed = git("status", "--porcelain", "--", ".", f":!{OUT_REL}")
    return f"{label}-dirty" if changed else label


def main():
    try:
        revision = git("rev-parse", "HEAD")
        described = describe()
    except subprocess.CalledProcessError as err:
        sys.exit(f"could not read the revision from git: {err.stderr.strip()}")

    OUT.write_text(
        f"""/*
 * Psiphon Access
 * Copyright (C) 2026  Psiphon Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// Generated by tool/teleport-google/assets/stamp-build.py. Do not edit.
//
// The login page shows these so that the AGPL section 13 offer resolves to the
// build a user is actually talking to, rather than to whatever the default
// branch happens to be today.

/** ACCESS_SOURCE_URL is where the Corresponding Source is published. */
export const ACCESS_SOURCE_URL = '{SOURCE_URL}';

/** ACCESS_REVISION is the full commit this build was made from. */
export const ACCESS_REVISION = '{revision}';

/**
 * ACCESS_BUILD is the human-readable build label: the nearest tag, the short
 * commit, and a -dirty suffix when the tree had uncommitted changes.
 */
export const ACCESS_BUILD = '{described}';
""",
        encoding="utf8",
    )

    print(f"{OUT.relative_to(ROOT)}")
    print(f"  revision {revision}")
    print(f"  build    {described}")


if __name__ == "__main__":
    main()
